config/routes.rb
Getingblog::Application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :users
  get '/signup', to:'users#new' , via:'get'

  root :to => "home#index"

  resources :sessions ,only: [:new, :create, :destroy]
  get '/signin', to: 'sessions#new', via:'get'
  get '/signout', to: 'sessions#destroy', via:'delete'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  commenter  :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :name , :presence => true
  validates :title , :presence => true, :length => { :minimum => 5 }
  has_many :comments , :dependent => :destroy
  has_many :tags
  accepts_nested_attributes_for :tags , :allow_destroy => :true ,
                                :reject_if => proc{|attrs| attrs.all?{|k,v| v.blank?}}
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
           uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    params.permit!
    @post = Post.find (params[:post_id])
    @comment = @post.comments.create( params[:comment])
    redirect_to post_path(@post)
  end


  def destroy
    @post = Post.find (params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.tags.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content ,tags_attributes: [:id , :name , :post_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:error] = 'sign in!'
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def new

  end
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "hello" + @user.name
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  COLOR_SCHEMES = {
          1 => 'white',
          2 => 'black',
          3 => 'solarized-dark',
          4 => 'monokai',
        }
    COLOR_SCHEMES.default = 'white'

  def user_color_scheme_class
    COLOR_SCHEMES[current_user.try(:color_scheme_id)]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join( ", " )
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token,User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user= (user)
    @current_user = user
  end

  def current_user
    remenber_token = User.encrypt(cooikes[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div style="background-color: #DADADA;border: 1px solid #CCCCCC;margin-bottom: 5px;padding: 5px;">
  <p>
    <b>姓名:</b><%= comment.commenter %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    发表时间：<%= comment.created_at.to_s.delete "UTC" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to '删除', [comment.post, comment], method: :delete, data: { confirm: '你确定？' } %>
  </p>
  <p>内容：：<%= comment.body %> </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>


    <div class = "field">
      <%= f.label :commenter %>
      <br/>
      <%= f.text_field :commenter %>
    </div>

    <div class = "field"> <%= f.label :body %>
      <br/> <%= f.text_area :body %>
    </div>

    <div class = "actions" >
      <%= f.submit %>
    </div >

<% end %>

app/views/home/index.html.erb
<h1>Hello rails!!!</h1>

<%= link_to "MyBlog",posts_path%>

app/views/layouts/_header.html.erb
<div style="padding-right:10px;width: 1024px;height:30px;text-align:right;margin: 0 auto;background-color: #BBBBBB;line-height: 30px;">

    <%= link_to '首页', root_path %>&nbsp;&nbsp;

          <%= link_to '我的中心', '#' %>&nbsp;&nbsp;
          <%= link_to '退出登录', signout_path,method: 'delete' %>&nbsp;&nbsp;

          <%= link_to '登录', signin_path %>&nbsp;&nbsp;
          <%= link_to '注册', signup_path %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title> Blog </title>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tag %>
</head>
<body style = " background: #EEEEEE; margin:0 auto;" >
<%= render 'layouts/header' %>
<div style="width:1024px;margin:0 auto;">
  <% flash.each do |key, value| %>
  <%= value %> <% end %>

  <%= yield %>

  <div style="border: 1px solid #999999;background-color: #BBBBBB;width:500px;margin:20px 0 50px 0px;float:right">
  <%= debug(params) if Rails.env.development? %>
  </div>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <%= @post.tags.build %>
  <div class="field">
    <%= post_form.label :name %><br>
    <%= post_form.text_field :name %>
  </div>
  <div class="field">
    <%= post_form.label :title %><br>
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br>
    <%= post_form.text_area :content %>
  </div>
    <h2>Tags</h2>
    <%= render :partial => 'tags/form', :locals => {:form => post_form} %>
    <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.order("created_at DESC").each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td>创建时间：<%= post.created_at.to_s.delete "UTC" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          最后修改时间：<%= post.updated_at.to_s.delete "UTC" %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @post.title %></h1>
</p>

<p>
  作者：<%= @post.name %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  创建时间：<%= @post.created_at.to_s.delete "UTC" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  最后修改时间：<%= @post.updated_at.to_s.delete "UTC" %>
</p>


<p> <strong>内容：</strong> <%= @post.content %> </p>

<p> <b>标签 :</b> <%= join_tags(@post) %> </p>

<p style="font-size: 20px">\\\\评论列表\\\\</p>

<%= render @post.comments %>

<h2>发表评论: </h2>

<%= render "comments/form" %>

<%= link_to 'Edit Post' , edit_post_path(@post) %> | <%= link_to 'Back to Posts' , posts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
        您填写的表单有 <%= pluralize(@user.errors.count, "处错误") %>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
<% end %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
    <div class = "field" >
      <%= tag_form.label :name, '标签:' %>
      <%= tag_form.text_field :name %>
    </div >
    <% unless tag_form.object.nil? || tag_form.object.new_record? %>
        <div class = "field" >
          <%= tag_form.label :_destroy, 'Remove:' %>
          <%= tag_form.check_box :_destroy %>
        </div >
    <% end %>
<% end %>

app/views/users/new.html.erb
<% provide(:title,'用户注册') %>
<p><%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
<%= f.label :name ,"用户名："%>
<%= f.text_field :name %></p><p>
<%= f.label :email , "邮件：："%>
<%= f.text_field :email %></p><p>
<%= f.label :password, "密码：："%>
<%= f.password_field :password %></p><p>
<%= f.label :password_confirmation, "密码确认" %>
<%= f.password_field :password_confirmation %></p><p>
<%= f.submit "创建用户" %></p><p>
      <%= link_to "已注册？点此登录！", signin_path %>
<% end %>

app/views/users/show.html.erb
<% provide(:title ,@user.name + '的用户中心') %>

<h2>欢迎<%= @user.name %></h2>